import streamlit as st

st.title(":wave: Welcome to StockLab!")

st.markdown(
    """
    **StockLab** is a minimalistic interactive dashboard built for comprehensive stock market analysis, visual exploration of historical data, and quantitative time series forecasting using the [Prophet model](https://facebook.github.io/prophet/).  
    
    All stock market data are sourced directly from Yahoo! Finance through [yfinance API](https://pypi.org/project/yfinance/), encompassing a continuous range from the 1st January 2010 up to the present day. The available stock tickers for analysis are:
    
    - AAPL: Apple Inc.
    - AMZN: Amazon.com, Inc.
    - GOOG: Alphabet Inc. (Google)
    - MSFT: Microsoft Corporation
    - GME: GameStop Corp.
    - TSLA: Tesla, Inc.
    - META: Meta Platforms (Facebook)
    - GS: Goldman Sachs Group, Inc.
    - DJIA: Dow Jones Industrial Average
    - SPX: S&P 500 Index
    - COMP: NASDAQ Composite Index


    **Note**:
    StockLab is intended exclusively for educational and exploratory purposes. It should be regarded as a computational "playground" only for experimentation with real-world data and forecasting techniques. The insights generated by this application do NOT constitute financial advice and must not be relied upon for investment decisions.
    
    """
)
