[project]
name = "stocklab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "plotly>=6.2.0",
    "prophet>=1.1.7",
    "streamlit>=1.47.1",
    "yfinance>=0.2.65",
]
